spring:
  application:
    name: chatbot-fiap

telegram:
  token: ${TELEGRAM-TOKEN}

open-weather-map:
  token: ${OPEN-WEATHER-TOKEN}

google:
  name: chatbot-fiap
  projectid: ${GOOGLE_CLOUD_PROJECT}
  languageCode: pt-BR

logging:
  level:
    web: fatal